# Generated by Django 5.1.2 on 2024-11-02 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(max_length=100, verbose_name='施設名')),
                ('address', models.CharField(max_length=255, verbose_name='住所')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='電話番号')),
                ('website_url', models.URLField(blank=True, verbose_name='ウェブサイトURL')),
                ('category', models.CharField(choices=[('restaurant', 'レストラン'), ('park', '公園'), ('hospital', '病院'), ('cafe', 'カフェ')], max_length=50, verbose_name='カテゴリ')),
                ('diaper_changing', models.BooleanField(default=False, verbose_name='おむつ替え台の有無')),
                ('nursing_room', models.BooleanField(default=False, verbose_name='授乳室の有無')),
                ('kids_space', models.BooleanField(default=False, verbose_name='キッズスペースの有無')),
                ('wheelchair_access', models.BooleanField(default=False, verbose_name='バリアフリー対応')),
                ('baby_car_rental', models.BooleanField(default=False, verbose_name='ベビーカーの貸し出し')),
                ('parking', models.BooleanField(default=False, verbose_name='駐車場の有無')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='コメント')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='評価（1〜5）')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='posts.facility')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
