# Generated by Django 5.1.2 on 2024-11-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='category',
            field=models.CharField(choices=[('restaurant', '飲食店'), ('recipe', 'レシピ'), ('park', '公園'), ('activity', 'アクティビティ'), ('support', '地域の支援'), ('education', '教育'), ('school', '学校'), ('experience', '経験談')], max_length=50, null=True, verbose_name='カテゴリ'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
